### PR TITLE
Added BTrack, an audio beat tracker originally by Adam Stark

### PR DESCRIPTION
**Pull request by mhusinsky**

### CODE REVIEW

**Comment by joreg** [comment]
great! but please also add the source for lib/VVVV.Audio.BTrack.dll so we can reproduce the build in case it needs a change. 
(yes, will also have to do this for the gist one)

**Comment by mhusinsky** [comment]
do you mean here in the repo, or is it okay to use a VVVV.Audio repo?
the way I see it, the VVVV.Audio repo would be the one where most of the dll sources for this repositories are originated. 
if a VVVV.Audio repository would be okay, [you can find the source in my fork in the BTrack branch](https://github.com/mhusinsky/VVVV.Audio/tree/BTrack).

**Comment by mhusinsky** [comment]
[here](https://github.com/mhusinsky/VVVV.Audio/tree/BTrack/Source/VVVV.Audio.BTrack), to be precise.
i still need to update the BTrackCLI.dll in there (the one in this repo is accidentially a debug build. the one i PRed here is a release build). and, of course, put the BTrackCLI sources online publicly. however, this still needs some cleanup

**Comment by joreg** [comment]
i mean here in the repo in a \src folder. the github action would then also build this csproj everytime. so we make sure this is a fully reproducible pack. the vvvv.audio parts are another thing. but here we'll only have these small bits that we best keep all in this one place

**Comment by mhusinsky** [comment]
made some updates with the requested changes. could you please review?

**Pull request merged**
